### ISSUE TITLE
Missing Dockerfile and docker-compose.yml files

### ISSUE THREAD

**Issue by florianjourda** [zenaton/examples-python#3]
The README tells we can use docker to run Zenaton, but the files to do it are missing :)

**Comment by Ciboulette** [comment]
Thanks @florianjourda 😊

@Yungbubu will correct this on monday! Sorry for the missing docker

**Comment by Yungbubu** [comment]
@florianjourda it's now fixed. (sorry for the delay, I was OFF since Friday)
